// ResolveAI v2 — Action + Feedback (wired to real data)

// ── Helpers ────────────────────────────────────────────────────────────────

function extractSubjectAndBody(draftText) {
  if (!draftText) return { subject: 'ResolveAI — Escalation', body: '' };
  const lines = draftText.split('\n');
  const subjectLine = lines.find((l) => l.toLowerCase().startsWith('subject:'));
  const subject = subjectLine
    ? subjectLine.replace(/^subject:\s*/i, '').trim()
    : 'ResolveAI — Escalation';
  // Body = everything after the first blank line following the subject
  const subjectIdx = subjectLine ? lines.indexOf(subjectLine) : -1;
  let bodyStart = subjectIdx + 1;
  while (bodyStart < lines.length && lines[bodyStart].trim() === '') bodyStart++;
  const body = lines.slice(bodyStart).join('\n').trim();
  return { subject, body };
}

function gmailComposeUrl(draftText) {
  const { subject, body } = extractSubjectAndBody(draftText);
  const base = 'https://mail.google.com/mail/?view=cm';
  return `${base}&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
}

// ── ActionPage ─────────────────────────────────────────────────────────────

function ActionPage({ setRoute }) {
  const [copiedIdx, setCopiedIdx] = React.useState(null);
  const [pdfMsg, setPdfMsg] = React.useState('');

  const state = window.resolveState || {};
  const activeDraft = state.activeDraft || state.allDrafts?.[0] || null;
  const data = state.data || {};

  const draftText = activeDraft?.draftTone
    ? (state.allDrafts?.find((d) => d.label === activeDraft.draftTone)?.body || activeDraft?.body || '')
    : activeDraft?.body || '';

  // ── Copy escalation ──────────────────────────────────────────────────────
  const handleCopy = () => {
    const text = draftText;
    if (navigator.clipboard && text) {
      navigator.clipboard.writeText(text).catch(() => {});
    }
    setCopiedIdx(0);
    setTimeout(() => setCopiedIdx(null), 2000);
    setTimeout(() => setRoute('feedback'), 400);
  };

  // ── Open Gmail ───────────────────────────────────────────────────────────
  const handleGmail = () => {
    const url = gmailComposeUrl(draftText);
    window.open(url, '_blank', 'noopener');
    setTimeout(() => setRoute('feedback'), 400);
  };

  // ── Download PDF ─────────────────────────────────────────────────────────
  const handlePdf = () => {
    setPdfMsg('Opening print dialog…');
    // Build a clean printable page
    const { subject, body } = extractSubjectAndBody(draftText);
    const printContent = `
      <html>
      <head>
        <title>${subject}</title>
        <style>
          body { font-family: Georgia, serif; max-width: 680px; margin: 60px auto; color: #111; line-height: 1.7; }
          h1 { font-size: 18px; font-weight: normal; margin-bottom: 8px; }
          .meta { font-size: 12px; color: #555; margin-bottom: 32px; }
          pre { font-family: inherit; white-space: pre-wrap; font-size: 14px; line-height: 1.8; }
          .footer { margin-top: 48px; font-size: 11px; color: #999; border-top: 1px solid #eee; padding-top: 16px; }
        </style>
      </head>
      <body>
        <div class="meta">ResolveAI · ${data.company_name || ''} · ${data.issue_type || ''}</div>
        <h1>${subject}</h1>
        <pre>${body.replace(/</g, '&lt;')}</pre>
        <div class="footer">Generated by ResolveAI · Personalise before sending · resolveai.vercel.app</div>
      </body>
      </html>
    `;
    const win = window.open('', '_blank');
    if (win) {
      win.document.write(printContent);
      win.document.close();
      setTimeout(() => { win.print(); setPdfMsg(''); }, 500);
    } else {
      setPdfMsg('Popup blocked — please allow popups and try again.');
    }
    setTimeout(() => setRoute('feedback'), 1200);
  };

  // ── Generate stronger ────────────────────────────────────────────────────
  const handleStronger = () => {
    // Switch to Firm tone if available, otherwise keep current
    if (state.allDrafts) {
      const firm = state.allDrafts.find((d) => d.label === 'Firm');
      if (firm) window.resolveState.activeDraft = firm;
    }
    setRoute('results');
    window.scrollTo({ top: 0, behavior: 'instant' });
  };

  const tiles = [
    {
      idx: '01',
      label: <span>Copy <em>escalation</em></span>,
      desc: 'Drop into any email client',
      action: handleCopy,
      active: copiedIdx === 0,
      activeLabel: '✓ Copied',
    },
    {
      idx: '02',
      label: <span>Open in <em>Gmail</em></span>,
      desc: 'Pre-filled subject and body — add the recipient',
      action: handleGmail,
    },
    {
      idx: '03',
      label: <span>Download <em>PDF</em></span>,
      desc: pdfMsg || 'Bundle draft + evidence',
      action: handlePdf,
    },
    {
      idx: '04',
      label: <span>Generate <em>stronger</em></span>,
      desc: 'Switch to the firm escalation tone',
      action: handleStronger,
    },
  ];

  return (
    <div className="fade-in">
      <section className="page upload-shell">
        <div className="sec-head">
          <div className="num">§ IV</div>
          <div className="lbl">
            <div className="title">Action</div>
            <div className="meta">Send · save · strengthen</div>
          </div>
        </div>

        <h1 className="h1" style={{ maxWidth: '20ch', marginBottom: 24 }}>
          Move it from your inbox <em>to theirs.</em>
        </h1>
        <p className="lede">
          Your draft is ready. Pick how you want to send it.
        </p>

        {/* Placeholder reminder */}
        <div style={{
          background: 'var(--warn-soft, #fff8e6)',
          border: '1px solid var(--warn, #b8860b)',
          borderRadius: 4,
          padding: '10px 16px',
          marginBottom: 28,
          fontSize: 13,
          color: 'var(--warn, #7a5700)',
          lineHeight: 1.55,
        }}>
          Before sending — replace <strong>[Your Name]</strong>, <strong>[Your Phone]</strong>, and <strong>[Your Email]</strong> in the draft with your real details.
        </div>

        <div className="action-grid">
          {tiles.map((t) => (
            <button
              key={t.idx}
              className="action-tile"
              onClick={t.action}
              style={t.active ? { borderColor: 'var(--accent)' } : {}}
            >
              <span className="idx">{t.idx}</span>
              <span>
                <div className="label">{t.active ? t.activeLabel : t.label}</div>
                <div className="desc">{t.desc}</div>
              </span>
              <span className="arrow">→</span>
            </button>
          ))}
        </div>

        <p style={{
          marginTop: 56,
          fontFamily: 'var(--serif)',
          fontStyle: 'italic',
          fontSize: 22,
          lineHeight: 1.4,
          color: 'var(--ink-2)',
          maxWidth: '52ch',
          letterSpacing: '-0.008em',
        }}>
          A clear, deadline-driven escalation is more likely to be taken seriously than a follow-up support ticket.
        </p>

        <FeedbackBlock />
      </section>
    </div>
  );
}

// ── FeedbackBlock (shared) ─────────────────────────────────────────────────

function FeedbackBlock() {
  const [selected, setSelected] = React.useState(null);
  const options = ['Got refund', 'Company responded', 'Still unresolved'];

  const messages = {
    'Got refund': '— Excellent. We learn from every win.',
    'Company responded': '— Good. Keep us posted if you need a follow-up draft.',
    'Still unresolved': '— We’ll suggest the next escalation tier. Check your inbox.',
  };

  return (
    <div className="feedback">
      <div className="topline">§ V — close the loop</div>
      <h3>Did this <em>help?</em></h3>
      <div className="feedback-options">
        {options.map((o) => (
          <button
            key={o}
            className={'feedback-opt' + (selected === o ? ' is-selected' : '')}
            onClick={() => setSelected(o)}
          >
            {o}
          </button>
        ))}
      </div>
      <div className={'feedback-thanks' + (selected ? ' show' : '')}>
        {selected && messages[selected]}
      </div>
    </div>
  );
}

// ── Feedback page ──────────────────────────────────────────────────────────

function Feedback({ setRoute }) {
  return (
    <div className="fade-in">
      <section className="page upload-shell" style={{ maxWidth: 880, margin: '0 auto' }}>
        <div className="sec-head">
          <div className="num">§ V</div>
          <div className="lbl">
            <div className="title">Sent</div>
            <div className="meta">Awaiting reply</div>
          </div>
        </div>

        <h1 className="h1" style={{ maxWidth: '18ch', marginBottom: 24 }}>
          Your escalation is <em>on its way.</em>
        </h1>
        <p className="lede" style={{ marginBottom: 0 }}>
          We&rsquo;ll keep this draft available for an hour, then it&rsquo;s gone.
        </p>

        <FeedbackBlock />

        <div style={{
          marginTop: 56,
          paddingTop: 32,
          borderTop: '1px solid var(--line)',
          display: 'flex',
          gap: 16,
          flexWrap: 'wrap',
        }}>
          <button
            className="btn btn-secondary"
            onClick={() => {
              window.resolveState = null;
              setRoute('landing');
              window.scrollTo({ top: 0, behavior: 'instant' });
            }}
          >
            Start a new dispute <span className="arrow">→</span>
          </button>
        </div>
      </section>
    </div>
  );
}

window.ActionPage = ActionPage;
window.Feedback = Feedback;
